### ISSUE TITLE
Nuget is not fable compatible

### ISSUE THREAD

**Issue by Zaid-Ajaj** [tforkmann/Feliz.ReactFlow#1]
Hi @tforkmann it seems that the nuget package doesn't include any Fable sources which means it will break when installed from a project

![2021-04-09 12_26_19-C__Users_zaidn_Downloads_feliz reactflow 0 1 4](https://user-images.githubusercontent.com/13316248/114167189-f0a7b480-992e-11eb-9bf6-2d2fa889cf34.png)

You need to include the sources using
```xml
<ItemGroup>
    <Content Include="*.fsproj; *.fs; *.js;" Exclude="**\*.fs.js" PackagePath="fable\" />
</ItemGroup>
```
Also the dependency should be a non-dev dependency so you can remove `DevDependency="true"` from the femto metadata
Also this packages take too many nuget packages as dependencies

![2021-04-09 12_29_33-NuGet Gallery _ Feliz ReactFlow 0 1 4](https://user-images.githubusercontent.com/13316248/114167476-441a0280-992f-11eb-95a7-5d2827b24eea.png)

You only need `Feliz` as a dependency (update paket.references to only require Feliz). 

Preferably the target framework can be `netstandard2.0` for maximum compatibility with Fable projects that aren't using dotnet 5.0

**Comment by tforkmann** [comment]
Hi Zaid,

will try to fix over the weekend!

Best,

Tim

**Comment by tforkmann** [comment]
Should be fine now.
![image](https://user-images.githubusercontent.com/4168951/114259231-bb51a400-99cc-11eb-97b7-0c85f3faaf32.png)

Closing with 7e22576
